### ISSUE TITLE
Non-standard code being thrown

### ISSUE THREAD

**Issue by thebuidler** [MetaMask/rpc-errors#49]
Getting an error that isn't included in this list. I'm not familiar with what to do about that nor where the error is originating from:
```
MetaMask - RPC Error: The execution failed due to an exception. {code: -32016, message: 'The execution failed due to an exception.', data: 'Reverted'}
```

1. Any suggestions on how to troubleshoot these scenarios?
2. In this case I actually believe this is a `require()` in the contract function. Would that even make sense here? The error is actually being thrown _before_ a user is even prompted to submit the tx.
3. Who could be throwing these errors? I imagine this is either on the contract dev or the RPC client?

**Comment by thebuidler** [comment]
Bump -- still don't know what's going on here, sorry

**Comment by rekmarks** [comment]
Hi @thebuidler, thank you for creating this issue. I believe this error is coming from your RPC endpoint, whether that's local via Hardhat / Ganache, or remote via Infura or some other provider. This package is mostly about creating error objects that match existing standards; I suggest you take a look at the Ethereum Stackexchange, the `geth` GitHub repository, or similar locations.

Some references here:
- https://github.com/ethereum/web3.py/issues/2134
- https://ethereum.stackexchange.com/questions/121785/gas-estimation-fails-on-gnosis-safe-transaction-service-api-gnosis-chain

Since this actually appears to be working as it should on our end, I'm going to close this issue. If you believe the error is being thrown due to something MetaMask is doing, please create an issue on https://github.com/MetaMask/metamask-extension or https://github.com/MetaMask/metamask-mobile, depending on your platform.
